# Generated by Django 4.2.1 on 2023-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_course_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fname', models.CharField(max_length=20)),
                ('student_lname', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20)),
                ('student_department', models.CharField(max_length=15)),
                ('student_university', models.CharField(max_length=20)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_status', models.CharField(max_length=10)),
                ('student_birthdate', models.DateField()),
                ('student_courses', models.ManyToManyField(to='mainApp.course')),
            ],
        ),
    ]
