# Generated by Django 4.2.1 on 2023-05-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_id', models.IntegerField(default=0)),
                ('course_department', models.CharField(max_length=200)),
                ('course_hours', models.IntegerField(default=0)),
                ('course_day', models.CharField(max_length=200)),
                ('course_hall', models.IntegerField(default=0)),
                ('course_students_count', models.IntegerField(default=0)),
            ],
        ),
    ]
