# Generated by Django 4.2.1 on 2023-05-22 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='student_courses',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
