# Generated by Django 4.2.1 on 2023-05-22 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_student_student_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_courses',
            new_name='student_course1',
        ),
        migrations.AddField(
            model_name='student',
            name='student_course2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_course3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
